// ===========================================================================
// AUTO-GENERATED FROM /shared/domain/validation/index.js
// DO NOT EDIT — run `npm run sync:validation` at repo root to regenerate.
// Hash verified by scripts/check-validation.js (pre-build, pre-test).
// ===========================================================================
'use strict';

/*
 * shared/domain/validation
 *
 * Single source of truth for item/header validation across backend and frontend.
 *
 * TRUST BOUNDARY (Phase 1 contract):
 *   - Frontend payload values:        UNTRUSTED. Always re-validated server-side.
 *   - Backend `normalized` output:    TRUSTED. This is what gets persisted.
 *   - DB-persisted values:            TRUSTED. Read back without re-coercion.
 *
 * If FE-computed normalized != BE-computed normalized, the backend MUST reject
 * with VALIDATION_MISMATCH (HTTP 422). Silent server-side "correction" is forbidden.
 *
 * Frontend copy of this module is auto-generated by scripts/sync-validation.js
 * and guarded by scripts/check-validation.js (SHA-256 sidecar).
 * Do NOT edit the frontend copy directly.
 */

const normalization = require('./normalization');
const errorCodes    = require('./errorCodes');
const { validateItem }   = require('./itemRules');
const { validateHeader } = require('./headerRules');

module.exports = {
    validateItem,
    validateHeader,

    ...errorCodes,
    ...normalization,
};
