const { db, initDb } = require('../../db/db');
const customerService = require('../../services/customerService');
const certificateService = require('../../services/v2/certificateService');
const photoCertRepo = require('../../repositories/photoCertificateRepository');

describe('certificate generation across certificate types', () => {
    const createdIds = [];
    const createdCustomerIds = [];

    beforeAll(() => {
        initDb();
    });

    afterEach(() => {
        while (createdIds.length) {
            const { table, id } = createdIds.pop();
            try { db.prepare(`DELETE FROM ${table} WHERE id = ?`).run(id); } catch (_) {}
        }

        while (createdCustomerIds.length) {
            const id = createdCustomerIds.pop();
            try { db.prepare('DELETE FROM customer WHERE id = ?').run(id); } catch (_) {}
        }
    });

    async function createCustomer(label) {
        const phone = String(Date.now() + Math.floor(Math.random() * 1000)).slice(-10);
        const customer = await customerService.createCustomer({
            name: `TEST ${label}`,
            phone,
            notes: `Generated by ${label} certificate test`
        });

        createdCustomerIds.push(customer.id);
        return customer;
    }

    it('creates a gold certificate with persisted item totals', async () => {
        const customer = await createCustomer('GOLD CERT');

        const ts = new Date().toISOString();
        let certificate;

        db.transaction(() => {
            certificate = certificateService._createCertificateWork('gold', {
                customer_id: customer.id,
                status: 'TODO',
                mode_of_payment: 'Cash',
                gst: false,
                items: [
                    {
                        name: 'Test Gold Ring',
                        item_name: 'Test Gold Ring',
                        item_type: 'Ring',
                        gross_weight: 10.5,
                        test_weight: 0.2,
                        purity: 91.6,
                        rate_per_gram: 6100,
                        returned: false,
                        certificate_number: 'A01'
                    }
                ]
            }, ts, db);
        })();

        createdIds.push({ table: 'gold_certificate_item', id: certificate.items[0].id });
        createdIds.push({ table: 'gold_certificate', id: certificate.id });

        const saved = certificateService.getCertificate('gold', certificate.id);

        expect(saved.id).toBe(certificate.id);
        expect(saved.items).toHaveLength(1);
        expect(saved.items[0].fine_weight).toBeGreaterThan(0);
        expect(saved.items[0].item_total).toBeGreaterThan(0);
    });

    it('creates a silver certificate without schema errors and stores calculated fields', async () => {
        const customer = await createCustomer('SILVER CERT');

        const ts = new Date().toISOString();
        let certificate;

        db.transaction(() => {
            certificate = certificateService._createCertificateWork('silver', {
                customer_id: customer.id,
                status: 'TODO',
                items: [
                    {
                        name: 'Test Silver Chain',
                        item_name: 'Test Silver Chain',
                        item_type: 'Chain',
                        gross_weight: 28.4,
                        test_weight: 0.4,
                        purity: 92.1,
                        returned: false,
                        item_total: 850,
                        certificate_number: 'S01'
                    }
                ]
            }, ts, db);
        })();

        createdIds.push({ table: 'silver_certificate_item', id: certificate.items[0].id });
        createdIds.push({ table: 'silver_certificate', id: certificate.id });

        const saved = certificateService.getCertificate('silver', certificate.id);

        expect(saved.id).toBe(certificate.id);
        expect(saved.items).toHaveLength(1);
        expect(saved.items[0].fine_weight).toBeGreaterThan(0);
        expect(saved.items[0].item_total).toBeGreaterThanOrEqual(0);
    });

    it('creates a photo certificate and persists its item rows', async () => {
        const customer = await createCustomer('PHOTO CERT');

        const certificate = await photoCertRepo.create(
            customer.id,
            [
                {
                    name: 'Test Photo Sample',
                    item_name: 'Test Photo Sample',
                    item_type: 'Photo Sample',
                    gross_weight: 8.5,
                    test_weight: 0,
                    purity: 88.8,
                    returned: false,
                    certificate_number: 'P01'
                }
            ],
            {
                mode_of_payment: 'Cash',
                total: 450,
                gst: 0
            },
            'TODO'
        );

        createdIds.push({ table: 'photo_certificate_item', id: certificate.items[0].id });
        createdIds.push({ table: 'photo_certificate', id: certificate.id });

        const saved = photoCertRepo.findById(certificate.id);

        expect(saved.id).toBe(certificate.id);
        expect(saved.items).toHaveLength(1);
        expect(saved.items[0].item_total).toBeGreaterThanOrEqual(0);
    });
});
