/* eslint-disable strict */
'use strict';

/*
 * shared/domain/validation
 *
 * Single source of truth for item/header validation across backend and frontend.
 *
 * TRUST BOUNDARY (Phase 1 contract):
 *   - Frontend payload values:        UNTRUSTED. Always re-validated server-side.
 *   - Backend `normalized` output:    TRUSTED. This is what gets persisted.
 *   - DB-persisted values:            TRUSTED. Read back without re-coercion.
 *
 * If FE-computed normalized != BE-computed normalized, the backend MUST reject
 * with VALIDATION_MISMATCH (HTTP 422). Silent server-side "correction" is forbidden.
 *
 * Frontend copy of this module is auto-generated by scripts/sync-validation.js
 * and guarded by scripts/check-validation.js (SHA-256 sidecar).
 * Do NOT edit the frontend copy directly.
 */

const normalization = require('./normalization');
const errorCodes    = require('./errorCodes');
const { validateItem }   = require('./itemRules');
const { validateHeader } = require('./headerRules');

module.exports = {
    validateItem,
    validateHeader,

    // Explicit exports from errorCodes
    ERROR_CODES: errorCodes.ERROR_CODES,
    SEVERITY: errorCodes.SEVERITY,
    SOURCE: errorCodes.SOURCE,
    SUPPORTED_WORKFLOW_TYPES: errorCodes.SUPPORTED_WORKFLOW_TYPES,
    OPERATIONS: errorCodes.OPERATIONS,
    ACTORS: errorCodes.ACTORS,

    // Explicit exports from normalization
    WEIGHT_DECIMAL_PLACES: normalization.WEIGHT_DECIMAL_PLACES,
    MAX_WEIGHT_GRAMS: normalization.MAX_WEIGHT_GRAMS,
    MIN_POSITIVE_WEIGHT: normalization.MIN_POSITIVE_WEIGHT,
    EQUALITY_EPSILON: normalization.EQUALITY_EPSILON,
    coerceNumber: normalization.coerceNumber,
    normalizeWeight: normalization.normalizeWeight,
    subtractWeights: normalization.subtractWeights,
    safeEquals: normalization.safeEquals,
    isPositiveWeight: normalization.isPositiveWeight,
    isNonNegativeWeight: normalization.isNonNegativeWeight,
    isWithinMax: normalization.isWithinMax,
    isWeightEmpty: normalization.isWeightEmpty,
};
